---
udhcpd_static_leases:
  - mac: 00:02:95:00:52:ae
    ip: 10.42.42.120
  - mac: 00:02:95:00:5a:a4
    ip: 10.42.42.121
  - mac: 00:02:95:00:7c:07
    ip: 10.42.42.122

# how many modems are connected via a quadmodem?
gsm_modems: 3
